### ISSUE TITLE
`src/common/version.h` gets generated wrongly.

### ISSUE THREAD

**Issue by felixbecker2** [ahngoo8Gongi/claws-mail#3]
If I use the claws mail source from [`git://github.com/ahngoo8Gongi/claws-mail.git`](git://github.com/ahngoo8Gongi/claws-mail.git), build fails for me because `src/common/version.h` gets generated wrongly during `./configure`:

I do the following steps to start with a clean source:

```
rm -Rf claws-mail-protectedheaders
git clone git://github.com/ahngoo8Gongi/claws-mail.git claws-mail-protectedheaders
cd claws-mail-protectedheaders
git checkout protected-headers-21
NOCONFIGURE=1 ./autogen.sh
./configure
```

That `./configure` call creates a file `src/common/version.h` which contains the line

```
#define VERSION			"8c0ef3.8c0ef3.8c0ef3"
```

(And that `8c0ef3` corresponds to the latest git commit hash: This are the first 6 characters of the output of `git rev-parse --short HEAD`).

`make` then fails on it with

```
/bin/sh ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../..  -I../../intl -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -pthread   -DLOCALEDIR=\""/usr/share/locale"\" -DPLUGINDIR=\"/usr/lib/claws-mail/plugins/\" -DDATAROOTDIR=\""/usr/share"\" -DDESKTOPFILEPATH=\"/usr/share/applications/claws-mail.desktop\" -DGTK_DISABLE_DEPRECATED  -Wall -Wno-pointer-sign -g0 -march=x86-64 -mtune=native -O3 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -fomit-frame-pointer -fPIC -MT xmlprops.lo -MD -MP -MF .deps/xmlprops.Tpo -c -o xmlprops.lo xmlprops.c
In file included from claws.c:42:
claws.c: In function ‘claws_get_version’:
version.h:32:54: error: invalid suffix "c0ef3" on integer constant
   32 | #define VERSION_NUMERIC         MAKE_NUMERIC_VERSION(8c0ef3, 8c0ef3, \
      |                                                      ^~~~~~
version.h:25:54: note: in definition of macro ‘MAKE_NUMERIC_VERSION’
   25 | #define MAKE_NUMERIC_VERSION(a, b, c, d) ((((guint32)a) << 24) | (((guint32)b) << 16) | \
      |                                                      ^
claws.c:143:16: note: in expansion of macro ‘VERSION_NUMERIC’
  143 |         return VERSION_NUMERIC;
      |                ^~~~~~~~~~~~~~~
version.h:32:62: error: invalid suffix "c0ef3" on integer constant
   32 | #define VERSION_NUMERIC         MAKE_NUMERIC_VERSION(8c0ef3, 8c0ef3, \
      |                                                              ^~~~~~
version.h:25:77: note: in definition of macro ‘MAKE_NUMERIC_VERSION’
   25 | #define MAKE_NUMERIC_VERSION(a, b, c, d) ((((guint32)a) << 24) | (((guint32)b) << 16) | \
      |                                                                             ^
claws.c:143:16: note: in expansion of macro ‘VERSION_NUMERIC’
  143 |         return VERSION_NUMERIC;
      |                ^~~~~~~~~~~~~~~
version.h:33:54: error: invalid suffix "c0ef3" on integer constant
   33 |                                                      8c0ef3, 0)
      |                                                      ^~~~~~
version.h:26:54: note: in definition of macro ‘MAKE_NUMERIC_VERSION’
   26 |                                           (((guint32)c) <<  8) |  ((guint32)d)      )
      |                                                      ^
claws.c:143:16: note: in expansion of macro ‘VERSION_NUMERIC’
  143 |         return VERSION_NUMERIC;
      |                ^~~~~~~~~~~~~~~
claws.c:144:1: warning: control reaches end of non-void function [-Wreturn-type]
  144 | }
      | ^
```

If I use as source [`git://github.com/ahngoo8Gongi/claws-mail.git`](git://github.com/ahngoo8Gongi/claws-mail.git) but with the master branch, `src/common/version.h` gets generated wrongly as well. Also if I start with the branch `protected-headers-21` and then manually reverse-apply the patch [`https://www.thewildbeast.co.uk/claws-mail/bugzilla/attachment.cgi?id=2260`](https://www.thewildbeast.co.uk/claws-mail/bugzilla/attachment.cgi?id=2260), `src/common/version.h` gets generated wrongly (the problematic line then even reads  
`#define VERSION			"8c0ef3-dirty.8c0ef3-dirty.8c0ef3"`).

If I directly use [`git://git.claws-mail.org/claws.git`](git://git.claws-mail.org/claws.git) as source, `src/common/version.h` gets generated correctly:

```
#define VERSION			"3.18.0git297"
```

Could it be that `./configure` needs the data that also `git describe --tags` uses? In your git repo, `git describe --tags` fails with `fatal: No names found, cannot describe anything.`, but in the official repo it outputs `3.18.0-297-g32bc9be42`.

---

*See also [https://www.thewildbeast.co.uk/claws-mail/bugzilla/show_bug.cgi?id=4426#c22](https://www.thewildbeast.co.uk/claws-mail/bugzilla/show_bug.cgi?id=4426#c22) and following comments.*

**Comment by ahngoo8Gongi** [comment]
Dear Felix, thanks for pointing this out. Seems to be an issue with the git repo. Interestingly, in my local clone of the repo I get

#git describe --tags
3.18.0-304-gaa1c37c39

I'll have a look into that later.

**Comment by ahngoo8Gongi** [comment]
I just pushed tags to this repo. Can you have a retry?

**Comment by felixbecker2** [comment]
> I just pushed tags to this repo. Can you have a retry?

Yes, this makes it working and fixes the issue for me.

I request closing als resolved.



-- 
"Sometimes I define a nerd as somebody who thinks that the purpose of
communication is to submit your ideas to peer review. And normal people
understand that the primary purpose of communication is to negotiate
alignment. And these purposes tend to conflict."

-- Joscha Bach
